// export const BASE_URL = 'https://al-electronics.uz/'

export const SUPPORT_LOCALES = ["en", "ru", "uz"];

export const interval_date = ["hours", "days", "month", "days_period"];
// export const interval_date = ["hours", "days"];
export const interval_visits = [
  "country",
  "country-visitis",
  "visits-device",
  "registrated",
  "region-visits",
];

export const weekStartNum = 0 | 1 | 2 | 3 | 4 | 5 | 6;
export const weekStartStr = "0" | "1" | "2" | "3" | "4" | "5" | "6";
export const hours = [
  "00:00",
  "01:00",
  "02:00",
  "03:00",
  "04:00",
  "05:00",
  "06:00",
  "07:00",
  "08:00",
  "09:00",
  "10:00",
  "11:00",
  "12:00",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
  "17:00",
  "18:00",
  "19:00",
  "20:00",
  "21:00",
  "22:00",
  "23:00",
];

export const regions = [
  {
    ru: "Ташкент",
    slug: "tashkent",
    color: "#346DC4",
  },
  {
    ru: "Фергана",
    slug: "fergana",
    color: "#A9A9A9",
  },
  {
    ru: "Самарканд",
    slug: "samarkand",
    color: "#5D9ED6",
  },
  {
    ru: "Хорезм",
    slug: "khorezm",
    color: "#28487B",
  },
  {
    ru: "Каракалпакистан",
    slug: "karakalpakistan",
    color: "#636363",
  },
  {
    ru: "Андижан",
    slug: "andijan",
    color: "#F58637",
  },
  {
    ru: "Навоий",
    slug: "navoi",
    color: "#FFC400",
  },
  {
    ru: "Жиззах",
    slug: "jizzakh",
    color: "#6FB245",
  },
  {
    ru: "Букхара",
    slug: "bukhara",
    color: "#A04204",
  },
];

export const fakeData = [
  {
    country: {
      slug: "UZ",
      name: "Узбекистан",
    },
    os_type: "IOS",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "UZ",
      name: "Узбекистан",
    },
    os_type: "Android",
    device_type: "Tv",
    total_count: 50,
  },
  {
    country: {
      slug: "AF",
      name: "Афганистан",
    },
    os_type: "IOS",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "AL",
      name: "Албания",
    },
    os_type: "Tizen",
    device_type: "Tv",
    total_count: 50,
  },
  {
    country: {
      slug: "AS",
      name: "American Samoa",
    },
    os_type: "Android",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "UZ",
      name: "Узбекистан",
    },
    os_type: "IOS",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "UZ",
      name: "Узбекистан",
    },
    os_type: "Android",
    device_type: "Tv",
    total_count: 50,
  },
  {
    country: {
      slug: "AF",
      name: "Афганистан",
    },
    os_type: "IOS",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "AL",
      name: "Албания",
    },
    os_type: "Tizen",
    device_type: "Tv",
    total_count: 50,
  },
  {
    country: {
      slug: "AS",
      name: "American Samoa",
    },
    os_type: "Android",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "UZ",
      name: "Узбекистан",
    },
    os_type: "IOS",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "UZ",
      name: "Узбекистан",
    },
    os_type: "Android",
    device_type: "Tv",
    total_count: 50,
  },
  {
    country: {
      slug: "AF",
      name: "Афганистан",
    },
    os_type: "IOS",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "AL",
      name: "Албания",
    },
    os_type: "Tizen",
    device_type: "Tv",
    total_count: 50,
  },
  {
    country: {
      slug: "AS",
      name: "American Samoa",
    },
    os_type: "Android",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "UZ",
      name: "Узбекистан",
    },
    os_type: "IOS",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "UZ",
      name: "Узбекистан",
    },
    os_type: "Android",
    device_type: "Tv",
    total_count: 50,
  },
  {
    country: {
      slug: "AF",
      name: "Афганистан",
    },
    os_type: "IOS",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "AL",
      name: "Албания",
    },
    os_type: "Tizen",
    device_type: "Tv",
    total_count: 50,
  },
  {
    country: {
      slug: "AS",
      name: "American Samoa",
    },
    os_type: "Android",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "UZ",
      name: "Узбекистан",
    },
    os_type: "IOS",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "UZ",
      name: "Узбекистан",
    },
    os_type: "Android",
    device_type: "Tv",
    total_count: 50,
  },
  {
    country: {
      slug: "AF",
      name: "Афганистан",
    },
    os_type: "IOS",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "AL",
      name: "Албания",
    },
    os_type: "Tizen",
    device_type: "Tv",
    total_count: 50,
  },
  {
    country: {
      slug: "AS",
      name: "American Samoa",
    },
    os_type: "Android",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "UZ",
      name: "Узбекистан",
    },
    os_type: "IOS",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "UZ",
      name: "Узбекистан",
    },
    os_type: "Android",
    device_type: "Tv",
    total_count: 50,
  },
  {
    country: {
      slug: "AF",
      name: "Афганистан",
    },
    os_type: "IOS",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "AL",
      name: "Албания",
    },
    os_type: "Tizen",
    device_type: "Tv",
    total_count: 50,
  },
  {
    country: {
      slug: "AS",
      name: "American Samoa",
    },
    os_type: "Android",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "UZ",
      name: "Узбекистан",
    },
    os_type: "IOS",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "UZ",
      name: "Узбекистан",
    },
    os_type: "Android",
    device_type: "Tv",
    total_count: 50,
  },
  {
    country: {
      slug: "AF",
      name: "Афганистан",
    },
    os_type: "IOS",
    device_type: "Smartphone",
    total_count: 50,
  },
  {
    country: {
      slug: "AL",
      name: "Албания",
    },
    os_type: "Tizen",
    device_type: "Tv",
    total_count: 50,
  },
  {
    country: {
      slug: "AS",
      name: "American Samoa",
    },
    os_type: "Android",
    device_type: "Smartphone",
    total_count: 50,
  },
];

export const COUNTRY_CHOICES = {
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  BN: "Brunei",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CK: "Cook Islands",
  CR: "Costa Rica",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  TP: "East Timor",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  ET: "Ethiopia",
  FK: "Falkland Islands",
  FO: "Faroe Islands",
  FJ: "Fiji Islands",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern territories",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island and McDonald Islands",
  VA: "Holy See (Vatican City State)",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle of Man",
  IL: "Israel",
  IT: "Italy",
  CI: "Ivory Coast",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Laos",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libyan Arab Jamahiriya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MK: "North Macedonia",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia, Federated States of",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  AN: "Netherlands Antilles",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  KP: "North Korea",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestine",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Reunion",
  RO: "Romania",
  RU: "Russian Federation",
  RW: "Rwanda",
  SH: "Saint Helena",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  PM: "Saint Pierre and Miquelon",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome and Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia and the South Sandwich Islands",
  KR: "South Korea",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard and Jan Mayen",
  SZ: "Swaziland",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syria",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  CD: "The Democratic Republic of Congo",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks and Caicos Islands",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UM: "United States Minor Outlying Islands",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Vietnam",
  VG: "Virgin Islands, British",
  VI: "Virgin Islands, U.S.",
  WF: "Wallis and Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  ALL: "All Countries",
  None: "Unknown",
};

// export const OS_CHOICES = [
//   "android", "Android", "ios", "iOS", "windows"
// ]

export const OS_CHOICES = [
  "android",
  "Android",
  "ios",
  "iOS",
  "windows",
  "Windows",
  "linux",
  "Linux",
  "chromeos",
  "Chrome OS",
  "bsd",
  "BSD",
  "tizen",
  "Tizen",
  "tvos",
  "Apple TV",
  "other",
  "Other",
];

export const DEVICE_CHOICES = [
  "smartphone",
  "Smartphone",
  "browser",
  "Browser",
  "tv",
  "TV",
  "other",
  "Other",
];
